// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opain.Jarvis.Infraestructura.Datos;

#nullable disable

namespace Opain.Jarvis.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ContextoOpain))]
    [Migration("20240409223042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Aerolinea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IdEstado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PDFPasajeros")
                        .HasColumnType("int");

                    b.Property<string>("Sigla")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Aerolineas");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Aeropuertos", b =>
                {
                    b.Property<string>("CodigoIATA")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("CobroCausal64VuelosDom")
                        .HasColumnType("bit");

                    b.Property<string>("Pais")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("CodigoIATA");

                    b.ToTable("Aeropuertos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.CantidadPasajerosOperacionVuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodPasajero")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodPasajero");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVuelo");

                    b.ToTable("CantidadPasajerosOperacionVuelo");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.CategoriaPasajeros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPasajero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CategoriaPasajeros");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Causal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Tipo");

                    b.ToTable("Causales");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Ciudad", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IdEstado")
                        .HasColumnType("bit");

                    b.Property<string>("IdPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdPais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("EstadoProceso")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaVuelo")
                        .HasColumnType("date");

                    b.Property<string>("HoraLlegada")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("HoraVuelo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("IdAerolinea")
                        .HasColumnType("int");

                    b.Property<string>("MatriculaVuelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumeroVueloLlegada")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("OrigenDes")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("PagoCOP")
                        .HasColumnType("int");

                    b.Property<int>("PagoUSD")
                        .HasColumnType("int");

                    b.Property<string>("TipoVuelo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("TotalEmbarcados")
                        .HasColumnType("int");

                    b.Property<int?>("TotalEmbarcadosAdd")
                        .HasColumnType("int");

                    b.Property<int?>("TotalEmbarcados_LIQ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoProceso");

                    b.HasIndex("IdAerolinea");

                    b.ToTable("OperacionesVuelos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVueloErrores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("int");

                    b.Property<string>("TipoError")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("TipoValidacion")
                        .HasColumnType("int");

                    b.Property<int>("TipoValidacion2")
                        .HasColumnType("int");

                    b.Property<string>("Valores")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValoresNuevos")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdVuelo");

                    b.ToTable("OperacionesVuelosErrores");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVueloSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdOperacionVuelo")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("IdOperacionVuelo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("OperacionVueloSeguimiento");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Pais", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IdEstado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVuelo")
                        .HasColumnType("date");

                    b.Property<int>("IdCargue")
                        .HasColumnType("int");

                    b.Property<string>("IdCategoriaPasajero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("IdOperacionVuelo")
                        .HasColumnType("int");

                    b.Property<string>("MatriculaVuelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Motivo_exencion")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Realiza_viaje")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargue");

                    b.HasIndex("IdOperacionVuelo");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.PasajeroTransito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AerolineaLlegada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AerolineaSalida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("FechaHoraCargue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<int>("Firmado")
                        .HasColumnType("int");

                    b.Property<string>("HoraLlegada")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("HoraSalida")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("IdCargue")
                        .HasColumnType("int");

                    b.Property<int>("IdOperacionVuelo")
                        .HasColumnType("int");

                    b.Property<int>("IdVueloLlegada")
                        .HasColumnType("int");

                    b.Property<int>("IdVueloSalida")
                        .HasColumnType("int");

                    b.Property<string>("NombrePasajero")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumeroVueloLlegada")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumeroVueloSalida")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("TasaCobrada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCargue");

                    b.HasIndex("IdOperacionVuelo");

                    b.ToTable("PasajerosTransito");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.PoliticasDeTratamientoDeDatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptarPoliticas")
                        .HasColumnType("BIT");

                    b.Property<string>("Aerolinea")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Hora")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("PoliticasDeTratamientoDeDatos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RespuestaTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adjunto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTicket");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RespuestasTickets");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RolesUsuarios", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnOrder(0);

                    b.Property<string>("IdRol")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnOrder(1);

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("RolesUsuarios");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RutaArchivos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdOperacionVuelo")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("IdOperacionVuelo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RutaArchivos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.TasaAeroportuaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("ValorCOP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUSD")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TasasAeroportuarias");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adjunto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVuelo")
                        .HasColumnType("date");

                    b.Property<int>("IdAerolinea")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Seguimiento")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("IdAerolinea");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoConsulta");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Tripulantes", b =>
                {
                    b.Property<int>("IdTripulantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTripulantes"));

                    b.Property<string>("FuncionTripulante")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("LicenciaTripulante")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NombreTripulante")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("codigoAreolinea")
                        .HasColumnType("int");

                    b.HasKey("IdTripulantes");

                    b.HasIndex("codigoAreolinea");

                    b.ToTable("Tripulantes");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.U_Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("U_Catalogo");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.U_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCatalogo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCatalogo");

                    b.ToTable("U_Item");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Activo")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailConfirmed")
                        .HasColumnType("int");

                    b.Property<int>("LockoutEnabled")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumberConfirmed")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TwoFactorEnabled")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.UsuariosAerolineas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAerolinea")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdAerolinea");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuariosAerolineas");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.CantidadPasajerosOperacionVuelo", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.CategoriaPasajeros", "CategoriaPasajeros")
                        .WithMany()
                        .HasForeignKey("CodPasajero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPasajeros");

                    b.Navigation("OperacionesVuelo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.CategoriaPasajeros", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Causal", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item2")
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item")
                        .WithMany()
                        .HasForeignKey("Tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("U_Item");

                    b.Navigation("U_Item2");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Ciudad", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item")
                        .WithMany()
                        .HasForeignKey("EstadoProceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Aerolinea", "Aerolinea")
                        .WithMany("OperacionesVuelos")
                        .HasForeignKey("IdAerolinea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aerolinea");

                    b.Navigation("U_Item");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVueloErrores", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperacionesVuelo");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.OperacionesVueloSeguimiento", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item")
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdOperacionVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperacionesVuelo");

                    b.Navigation("U_Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Pasajero", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.RutaArchivos", "RutaArchivos")
                        .WithMany()
                        .HasForeignKey("IdCargue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdOperacionVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperacionesVuelo");

                    b.Navigation("RutaArchivos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.PasajeroTransito", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.RutaArchivos", "RutaArchivos")
                        .WithMany()
                        .HasForeignKey("IdCargue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdOperacionVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperacionesVuelo");

                    b.Navigation("RutaArchivos");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RespuestaTicket", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Ticket", "Ticket")
                        .WithMany("RespuestasTickets")
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("RespuestasTickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RolesUsuarios", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Rol", "Rol")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.RutaArchivos", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.OperacionesVuelo", "OperacionesVuelo")
                        .WithMany()
                        .HasForeignKey("IdOperacionVuelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperacionesVuelo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Ticket", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item2")
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Aerolinea", "Aerolinea")
                        .WithMany("Tickets")
                        .HasForeignKey("IdAerolinea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Tickets")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Item", "U_Item")
                        .WithMany()
                        .HasForeignKey("TipoConsulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aerolinea");

                    b.Navigation("U_Item");

                    b.Navigation("U_Item2");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Tripulantes", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Aerolinea", "Aerolinea")
                        .WithMany()
                        .HasForeignKey("codigoAreolinea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aerolinea");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.U_Item", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.U_Catalogo", "U_Catalogo")
                        .WithMany()
                        .HasForeignKey("IdCatalogo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("U_Catalogo");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.UsuariosAerolineas", b =>
                {
                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Aerolinea", "Aerolinea")
                        .WithMany("UsuariosAerolineas")
                        .HasForeignKey("IdAerolinea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opain.Jarvis.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuariosAerolineas")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Aerolinea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Aerolinea", b =>
                {
                    b.Navigation("OperacionesVuelos");

                    b.Navigation("Tickets");

                    b.Navigation("UsuariosAerolineas");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Rol", b =>
                {
                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Ticket", b =>
                {
                    b.Navigation("RespuestasTickets");
                });

            modelBuilder.Entity("Opain.Jarvis.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("RespuestasTickets");

                    b.Navigation("RolesUsuarios");

                    b.Navigation("Tickets");

                    b.Navigation("UsuariosAerolineas");
                });
#pragma warning restore 612, 618
        }
    }
}
